import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAuth } from "react-oidc-context";
import Link from "next/link";
import { useToken } from "../hooks/useToken";
import { Button } from "@mantine/core";
import LoginButton from "../components/LoginButton/LoginButton";
import { useEffect } from "react";

export default function Home() {
  const auth = useAuth();
  const token = useToken();

  useEffect(() => {
    if (!auth.isAuthenticated && !auth.isLoading) {
      auth.signinSilent();
    }
  }, [auth]);

  if (auth.isLoading) {
    return (
      <main className={styles.main}>
        <div>Loading...</div>
      </main>
    );
  }

  function handleLogout() {
    try {
      auth.signoutRedirect();
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {auth.isAuthenticated || token ? (
          <div>
            <h5 className={styles.title}>
              Your company is {token?.profile?.company?.[0].name}
            </h5>
            <h5 className={styles.title}>
              You are login as {auth.user?.profile.name}
            </h5>
            <Link href={"/voucher"}>Send Faktura</Link>
            <Button onClick={handleLogout}>logout</Button>
          </div>
        ) : (
          <div>
            <LoginButton />
          </div>
        )}
      </main>
    </div>
  );
}
